name: Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 054037112975.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t todo-list-app-int .

    - name: Tag Docker Image
      run: |
        docker tag todo-list-app-int:latest 054037112975.dkr.ecr.us-east-1.amazonaws.com/todo-list-app-int:latest

    - name: Push Docker Image to ECR
      run: |
        docker push 054037112975.dkr.ecr.us-east-1.amazonaws.com/todo-list-app-int:latest
