name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t <your-dockerhub-username>/todo-list-app .
        docker tag <your-dockerhub-username>/todo-list-app:latest <your-dockerhub-username>/todo-list-app
        docker push <your-dockerhub-username>/todo-list-app
